/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ApplicationLogo: typeof import('./../Components/ApplicationLogo.vue')['default']
    AuthenticatedLayout: typeof import('./../Layouts/AuthenticatedLayout.vue')['default']
    Checkbox: typeof import('./../Components/Checkbox.vue')['default']
    DangerButton: typeof import('./../Components/DangerButton.vue')['default']
    Dropdown: typeof import('./../Components/Dropdown.vue')['default']
    DropdownLink: typeof import('./../Components/DropdownLink.vue')['default']
    GuestLayout: typeof import('./../Layouts/GuestLayout.vue')['default']
    Head: typeof import('@inertiajs/vue3')['Head']
    InputError: typeof import('./../Components/InputError.vue')['default']
    InputLabel: typeof import('./../Components/InputLabel.vue')['default']
    Link: typeof import('@inertiajs/vue3')['Link']
    Modal: typeof import('./../Components/Modal.vue')['default']
    NavLink: typeof import('./../Components/NavLink.vue')['default']
    PrimaryButton: typeof import('./../Components/PrimaryButton.vue')['default']
    ResponsiveNavLink: typeof import('./../Components/ResponsiveNavLink.vue')['default']
    SecondaryButton: typeof import('./../Components/SecondaryButton.vue')['default']
    TextInput: typeof import('./../Components/TextInput.vue')['default']
  }
}
