/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ApplicationLogo: typeof import('./../../views/components/application-logo.vue')['default']
    AuthenticatedLayout: typeof import('./../../views/layouts/authenticated-layout.vue')['default']
    Checkbox: typeof import('./../../views/components/checkbox.vue')['default']
    DangerButton: typeof import('./../../views/components/danger-button.vue')['default']
    Dropdown: typeof import('./../../views/components/dropdown.vue')['default']
    DropdownLink: typeof import('./../../views/components/dropdown-link.vue')['default']
    GuestLayout: typeof import('./../../views/layouts/guest-layout.vue')['default']
    Head: typeof import('@inertiajs/vue3')['Head']
    InputError: typeof import('./../../views/components/input-error.vue')['default']
    InputLabel: typeof import('./../../views/components/input-label.vue')['default']
    Link: typeof import('@inertiajs/vue3')['Link']
    Modal: typeof import('./../../views/components/modal.vue')['default']
    NavLink: typeof import('./../../views/components/nav-link.vue')['default']
    PrimaryButton: typeof import('./../../views/components/primary-button.vue')['default']
    ResponsiveNavLink: typeof import('./../../views/components/responsive-nav-link.vue')['default']
    SecondaryButton: typeof import('./../../views/components/secondary-button.vue')['default']
    TextInput: typeof import('./../../views/components/text-input.vue')['default']
  }
}
